# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1415d37f64a8fcd8c00678d921cab03568b99eb584b90bc91bcd829c25e5b22930437c24baf71b0328525c5e52dc42f207b7eabe0fb28d2629cdfb2ebc5504cc

test:
  secret_key_base: 182a23f2313af0a6631308046c97faab756c2d3e877a6a063e78d12173502967f1c37e12d2902254300a6da2f79ded917780fd6d401f4d52a200818488e2922b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
